name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run Docker container
      run: |
        docker build -t my-python-app .
        docker run -it --rm --name my-running-app my-python-app
